var dir_c1682bf5ca5dd8722cf3dd209f110359 =
[
    [ "add_solver_util.cc", "add__solver__util_8cc.html", null ],
    [ "add_solver_util.h", "add__solver__util_8h.html", "add__solver__util_8h" ],
    [ "bilinear_product_util_test.cc", "bilinear__product__util__test_8cc.html", "bilinear__product__util__test_8cc" ],
    [ "binding_test.cc", "binding__test_8cc.html", "binding__test_8cc" ],
    [ "branch_and_bound_test.cc", "branch__and__bound__test_8cc.html", null ],
    [ "choose_best_solver_test.cc", "choose__best__solver__test_8cc.html", "choose__best__solver__test_8cc" ],
    [ "complementary_problem_test.cc", "complementary__problem__test_8cc.html", null ],
    [ "constraint_test.cc", "constraint__test_8cc.html", "constraint__test_8cc" ],
    [ "cost_test.cc", "cost__test_8cc.html", "cost__test_8cc" ],
    [ "create_constraint_test.cc", "create__constraint__test_8cc.html", "create__constraint__test_8cc" ],
    [ "decision_variable_test.cc", "decision__variable__test_8cc.html", "decision__variable__test_8cc" ],
    [ "diagonally_dominant_matrix_test.cc", "diagonally__dominant__matrix__test_8cc.html", "diagonally__dominant__matrix__test_8cc" ],
    [ "dreal_solver_test.cc", "dreal__solver__test_8cc.html", "dreal__solver__test_8cc" ],
    [ "equality_constrained_qp_solver_test.cc", "equality__constrained__qp__solver__test_8cc.html", "equality__constrained__qp__solver__test_8cc" ],
    [ "evaluator_base_test.cc", "evaluator__base__test_8cc.html", "evaluator__base__test_8cc" ],
    [ "generic_trivial_constraints.h", "generic__trivial__constraints_8h.html", [
      [ "GenericTrivialConstraint1", "classdrake_1_1solvers_1_1test_1_1_generic_trivial_constraint1.html", "classdrake_1_1solvers_1_1test_1_1_generic_trivial_constraint1" ]
    ] ],
    [ "generic_trivial_costs.h", "generic__trivial__costs_8h.html", [
      [ "GenericTrivialCost1", "classdrake_1_1solvers_1_1test_1_1_generic_trivial_cost1.html", "classdrake_1_1solvers_1_1test_1_1_generic_trivial_cost1" ],
      [ "GenericTrivialCost2", "classdrake_1_1solvers_1_1test_1_1_generic_trivial_cost2.html", "classdrake_1_1solvers_1_1test_1_1_generic_trivial_cost2" ]
    ] ],
    [ "gurobi_solver_grb_license_file_test.cc", "gurobi__solver__grb__license__file__test_8cc.html", null ],
    [ "gurobi_solver_test.cc", "gurobi__solver__test_8cc.html", "gurobi__solver__test_8cc" ],
    [ "indeterminate_test.cc", "indeterminate__test_8cc.html", "indeterminate__test_8cc" ],
    [ "integer_inequality_solver_test.cc", "integer__inequality__solver__test_8cc.html", "integer__inequality__solver__test_8cc" ],
    [ "integer_optimization_util_test.cc", "integer__optimization__util__test_8cc.html", "integer__optimization__util__test_8cc" ],
    [ "ipopt_solver_test.cc", "ipopt__solver__test_8cc.html", "ipopt__solver__test_8cc" ],
    [ "linear_complementary_problem_test.cc", "linear__complementary__problem__test_8cc.html", "linear__complementary__problem__test_8cc" ],
    [ "linear_program_examples.cc", "linear__program__examples_8cc.html", "linear__program__examples_8cc" ],
    [ "linear_program_examples.h", "linear__program__examples_8h.html", "linear__program__examples_8h" ],
    [ "linear_system_solver_test.cc", "linear__system__solver__test_8cc.html", "linear__system__solver__test_8cc" ],
    [ "mathematical_program_result_test.cc", "mathematical__program__result__test_8cc.html", "mathematical__program__result__test_8cc" ],
    [ "mathematical_program_test.cc", "mathematical__program__test_8cc.html", "mathematical__program__test_8cc" ],
    [ "mathematical_program_test_util.cc", "mathematical__program__test__util_8cc.html", "mathematical__program__test__util_8cc" ],
    [ "mathematical_program_test_util.h", "mathematical__program__test__util_8h.html", "mathematical__program__test__util_8h" ],
    [ "mixed_integer_optimization_test.cc", "mixed__integer__optimization__test_8cc.html", "mixed__integer__optimization__test_8cc" ],
    [ "mixed_integer_optimization_util_test.cc", "mixed__integer__optimization__util__test_8cc.html", "mixed__integer__optimization__util__test_8cc" ],
    [ "mixed_integer_rotation_constraint_corner_test.cc", "mixed__integer__rotation__constraint__corner__test_8cc.html", "mixed__integer__rotation__constraint__corner__test_8cc" ],
    [ "mixed_integer_rotation_constraint_internal_test.cc", "mixed__integer__rotation__constraint__internal__test_8cc.html", null ],
    [ "mixed_integer_rotation_constraint_limit_test.cc", "mixed__integer__rotation__constraint__limit__test_8cc.html", "mixed__integer__rotation__constraint__limit__test_8cc" ],
    [ "mixed_integer_rotation_constraint_test.cc", "mixed__integer__rotation__constraint__test_8cc.html", "mixed__integer__rotation__constraint__test_8cc" ],
    [ "moby_lcp_solver_test.cc", "moby__lcp__solver__test_8cc.html", null ],
    [ "mosek_solver_moseklm_license_file_test.cc", "mosek__solver__moseklm__license__file__test_8cc.html", null ],
    [ "mosek_solver_test.cc", "mosek__solver__test_8cc.html", "mosek__solver__test_8cc" ],
    [ "nlopt_solver_test.cc", "nlopt__solver__test_8cc.html", "nlopt__solver__test_8cc" ],
    [ "non_convex_optimization_util_test.cc", "non__convex__optimization__util__test_8cc.html", "non__convex__optimization__util__test_8cc" ],
    [ "nonlinear_program_test.cc", "nonlinear__program__test_8cc.html", "nonlinear__program__test_8cc" ],
    [ "optimization_examples.cc", "optimization__examples_8cc.html", "optimization__examples_8cc" ],
    [ "optimization_examples.h", "optimization__examples_8h.html", "optimization__examples_8h" ],
    [ "osqp_solver_test.cc", "osqp__solver__test_8cc.html", "osqp__solver__test_8cc" ],
    [ "plot_feasible_rotation_matrices.cc", "plot__feasible__rotation__matrices_8cc.html", "plot__feasible__rotation__matrices_8cc" ],
    [ "plot_rotation_mccormick_envelope.cc", "plot__rotation__mccormick__envelope_8cc.html", "plot__rotation__mccormick__envelope_8cc" ],
    [ "quadratic_program_examples.cc", "quadratic__program__examples_8cc.html", "quadratic__program__examples_8cc" ],
    [ "quadratic_program_examples.h", "quadratic__program__examples_8h.html", "quadratic__program__examples_8h" ],
    [ "rotation_constraint_test.cc", "rotation__constraint__test_8cc.html", "rotation__constraint__test_8cc" ],
    [ "rotation_constraint_visualization.cc", "rotation__constraint__visualization_8cc.html", "rotation__constraint__visualization_8cc" ],
    [ "rotation_constraint_visualization.h", "rotation__constraint__visualization_8h.html", "rotation__constraint__visualization_8h" ],
    [ "scaled_diagonally_dominant_matrix_test.cc", "scaled__diagonally__dominant__matrix__test_8cc.html", "scaled__diagonally__dominant__matrix__test_8cc" ],
    [ "scs_solver_test.cc", "scs__solver__test_8cc.html", "scs__solver__test_8cc" ],
    [ "second_order_cone_program_examples.cc", "second__order__cone__program__examples_8cc.html", "second__order__cone__program__examples_8cc" ],
    [ "second_order_cone_program_examples.h", "second__order__cone__program__examples_8h.html", "second__order__cone__program__examples_8h" ],
    [ "semidefinite_program_examples.cc", "semidefinite__program__examples_8cc.html", "semidefinite__program__examples_8cc" ],
    [ "semidefinite_program_examples.h", "semidefinite__program__examples_8h.html", "semidefinite__program__examples_8h" ],
    [ "snopt_solver_test.cc", "snopt__solver__test_8cc.html", "snopt__solver__test_8cc" ],
    [ "solve_test.cc", "solve__test_8cc.html", "solve__test_8cc" ],
    [ "solver_id_test.cc", "solver__id__test_8cc.html", null ],
    [ "solver_options_test.cc", "solver__options__test_8cc.html", "solver__options__test_8cc" ],
    [ "solver_type_converter_test.cc", "solver__type__converter__test_8cc.html", null ],
    [ "sos_basis_generator_test.cc", "sos__basis__generator__test_8cc.html", "sos__basis__generator__test_8cc" ],
    [ "sos_constraint_test.cc", "sos__constraint__test_8cc.html", "sos__constraint__test_8cc" ],
    [ "symbolic_extraction_test.cc", "symbolic__extraction__test_8cc.html", "symbolic__extraction__test_8cc" ],
    [ "system_identification_test.cc", "system__identification__test_8cc.html", "system__identification__test_8cc" ],
    [ "unrevised_lemke_solver_test.cc", "unrevised__lemke__solver__test_8cc.html", "unrevised__lemke__solver__test_8cc" ]
];