var dir_fc0178d6978c9fa2cad6ef3e048a60a7 =
[
    [ "test", "dir_b289c0902288a6c5dabd0a7f5af984d1.html", "dir_b289c0902288a6c5dabd0a7f5af984d1" ],
    [ "autodiff.cc", "autodiff_8cc.html", null ],
    [ "autodiff.h", "math_2autodiff_8h.html", "math_2autodiff_8h" ],
    [ "autodiff_gradient.cc", "autodiff__gradient_8cc.html", null ],
    [ "autodiff_gradient.h", "autodiff__gradient_8h.html", "autodiff__gradient_8h" ],
    [ "barycentric.cc", "barycentric_8cc.html", null ],
    [ "barycentric.h", "barycentric_8h.html", [
      [ "BarycentricMesh", "classdrake_1_1math_1_1_barycentric_mesh.html", "classdrake_1_1math_1_1_barycentric_mesh" ]
    ] ],
    [ "continuous_algebraic_riccati_equation.cc", "continuous__algebraic__riccati__equation_8cc.html", "continuous__algebraic__riccati__equation_8cc" ],
    [ "continuous_algebraic_riccati_equation.h", "continuous__algebraic__riccati__equation_8h.html", "continuous__algebraic__riccati__equation_8h" ],
    [ "convert_time_derivative.h", "convert__time__derivative_8h.html", "convert__time__derivative_8h" ],
    [ "cross_product.cc", "cross__product_8cc.html", null ],
    [ "cross_product.h", "cross__product_8h.html", "cross__product_8h" ],
    [ "discrete_algebraic_riccati_equation.cc", "discrete__algebraic__riccati__equation_8cc.html", "discrete__algebraic__riccati__equation_8cc" ],
    [ "discrete_algebraic_riccati_equation.h", "discrete__algebraic__riccati__equation_8h.html", "discrete__algebraic__riccati__equation_8h" ],
    [ "eigen_sparse_triplet.cc", "eigen__sparse__triplet_8cc.html", null ],
    [ "eigen_sparse_triplet.h", "eigen__sparse__triplet_8h.html", "eigen__sparse__triplet_8h" ],
    [ "evenly_distributed_pts_on_sphere.cc", "evenly__distributed__pts__on__sphere_8cc.html", "evenly__distributed__pts__on__sphere_8cc" ],
    [ "evenly_distributed_pts_on_sphere.h", "evenly__distributed__pts__on__sphere_8h.html", "evenly__distributed__pts__on__sphere_8h" ],
    [ "expmap.cc", "expmap_8cc.html", null ],
    [ "expmap.h", "expmap_8h.html", "expmap_8h" ],
    [ "gradient.cc", "gradient_8cc.html", null ],
    [ "gradient.h", "gradient_8h.html", [
      [ "Gradient", "structdrake_1_1math_1_1_gradient.html", "structdrake_1_1math_1_1_gradient" ],
      [ "Gradient< Derived, Nq, 1 >", "structdrake_1_1math_1_1_gradient_3_01_derived_00_01_nq_00_011_01_4.html", "structdrake_1_1math_1_1_gradient_3_01_derived_00_01_nq_00_011_01_4" ]
    ] ],
    [ "gradient_util.h", "gradient__util_8h.html", "gradient__util_8h" ],
    [ "gray_code.cc", "gray__code_8cc.html", "gray__code_8cc" ],
    [ "gray_code.h", "gray__code_8h.html", "gray__code_8h" ],
    [ "jacobian.cc", "jacobian_8cc.html", null ],
    [ "jacobian.h", "jacobian_8h.html", "jacobian_8h" ],
    [ "matrix_util.cc", "matrix__util_8cc.html", null ],
    [ "matrix_util.h", "matrix__util_8h.html", "matrix__util_8h" ],
    [ "normalize_vector.cc", "normalize__vector_8cc.html", null ],
    [ "normalize_vector.h", "normalize__vector_8h.html", "normalize__vector_8h" ],
    [ "orthonormal_basis.cc", "orthonormal__basis_8cc.html", null ],
    [ "orthonormal_basis.h", "orthonormal__basis_8h.html", "orthonormal__basis_8h" ],
    [ "quadratic_form.cc", "quadratic__form_8cc.html", "quadratic__form_8cc" ],
    [ "quadratic_form.h", "quadratic__form_8h.html", "quadratic__form_8h" ],
    [ "quaternion.cc", "quaternion_8cc.html", null ],
    [ "quaternion.h", "quaternion_8h.html", "quaternion_8h" ],
    [ "random_rotation.cc", "random__rotation_8cc.html", null ],
    [ "random_rotation.h", "random__rotation_8h.html", "random__rotation_8h" ],
    [ "rigid_transform.cc", "rigid__transform_8cc.html", null ],
    [ "rigid_transform.h", "rigid__transform_8h.html", [
      [ "RigidTransform", "classdrake_1_1math_1_1_rigid_transform.html", "classdrake_1_1math_1_1_rigid_transform" ]
    ] ],
    [ "roll_pitch_yaw.cc", "roll__pitch__yaw_8cc.html", "roll__pitch__yaw_8cc" ],
    [ "roll_pitch_yaw.h", "roll__pitch__yaw_8h.html", "roll__pitch__yaw_8h" ],
    [ "rotation_conversion_gradient.cc", "rotation__conversion__gradient_8cc.html", null ],
    [ "rotation_conversion_gradient.h", "rotation__conversion__gradient_8h.html", "rotation__conversion__gradient_8h" ],
    [ "rotation_matrix.cc", "rotation__matrix_8cc.html", null ],
    [ "rotation_matrix.h", "rotation__matrix_8h.html", "rotation__matrix_8h" ],
    [ "saturate.h", "saturate_8h.html", "saturate_8h" ],
    [ "wrap_to.h", "wrap__to_8h.html", "wrap__to_8h" ]
];